Dockerfile LABELs:

cisco.info.name
cisco.info.version
cisco.info.description 
cisco.info.author-link 
cisco.info.author-name 

cisco.descriptor-schema-version
cisco.cpuarch
cisco.env
cisco.type
cisco.depends-on.package
cisco.cpu-core
cisco.post_upgrade.initial_wait_time
cisco.post_upgrade.post_script

cicco.startup.image-name
cicco.startup.target
cicco.startup.tag
cicco.startup.rootfs
cisco.stop.target

cisco.monitor.script
cisco.monitor.period_seconds
cisco.monitor.initial_delay_seconds

cisco.resources.cpu
cisco.resources.disk
cisco.resources.memory
cisco.resources.platform-env
cisco.resources.profile
cisco.resources.host_mounts.description
cisco.resources.host_mounts.target_mount
cisco.resources.host_mounts.host_mount_path
cisco.resources.ramfs.size
cisco.resources.copy-from-host.parent-dirname
cisco.resources.copy-from-host.nested-dirname
cisco.resources.datastore
cisco.resources.visualization

cisco.resources.network.<number>.interface-name
cisco.resources.network.<number>.hint
cisco.resources.network.<number>.mac_forward_disable_mask
cisco.resources.network.<number>.mirroring
cisco.resources.network.<number>.mac_forward_enable_mask
cisco.resources.network.<number>.ipv6_required
cisco.resources.network.<number>.type
cisco.resources.network.<number>.ports.tcp
cisco.resources.network.<number>.ports.udp
cisco.resources.network.<number>.voice-lan
cisco.resources.network.<number>.description

cisco.resources.rootfs_expanded_size
cisco.resources.access-control
cisco.resources.provided
cisco.resources.rootfs_size
cisco.resources.filesystem.target
cisco.resources.filesystem.permission
cisco.resources.filesystem.accessmode
cisco.resources.filesystem.driver.type
cisco.resources.filesystem.driver.name
cisco.resources.filesystem.driver.wrpolicy
cisco.resources.filesystem.fstype
cisco.resources.filesystem.source.usage
cisco.resources.filesystem.source.name
cisco.resources.filesystem.source.file
cisco.resources.device-info
cisco.resources.broker
cisco.resources.oauth
cisco.resources.container-size
cisco.resources.cpu-topology.cores
cisco.resources.cpu-topology.socket-per-core
cisco.resources.extended-resources
cisco.resources.persistent_data_target
cisco.resources.chardev.dev
cisco.resources.chardev.type
cisco.resources.recommendations.profile
cisco.resources.recommendations.label
cisco.resources.recommendations.description
cisco.resources.seed-controller-certificate
cisco.resources.devices.<number>.type
cisco.resources.devices.<number>.label
cisco.resources.devices.<number>.usage
cisco.resources.devices.<number>.function
cisco.resources.devices.<number>.mandatory
cisco.resources.devices.<number>mount-point
cisco.resources.devices.<number>vendorID
cisco.resources.devices.<number>device-id
cisco.resources.devices.<number>device-directory-to-mount
cisco.resources.devices.<number>alias
cisco.resources.devices.<number>productid

cisco.rescue.remove_on_rescue
cisco.rescue.active_app_callback_on_reset
cisco.rescue.callback_timeout

